### PR TITLE
TypeError: this.input.chunk is not a function

### PR DESCRIPTION
**Pull request by milahu**
update dependencies
increment version

todo: release to npm

with the latest `@lezer/lr` the parser throws

> TypeError: this.input.chunk is not a function

### CODE REVIEW

**Comment by marijnh** [comment]
Could you say a bit more about how that problem occurs and how this PR helps?

**Comment by milahu** [comment]
package.json of  `@lezer/cpp 1.0.0` says

```json
{
  "dependencies": {
    "@lezer/highlight": "^1.0.0",
    "@lezer/lr": "^1.0.0"
  },
```

so npm installs `@lezer/lr 1.2.5`

```
pnpm list --depth 10 -r  

dependencies:
@lezer/cpp 1.0.0
├─┬ @lezer/highlight 1.1.3
│ └── @lezer/common 1.0.2
└─┬ @lezer/lr 1.2.5
  └── @lezer/common 1.0.2
```

but `@lezer/cpp 1.0.0` is not compatible with `@lezer/lr 1.2.5`

**Comment by milahu** [comment]
aah ... found my error

```diff
-  const source = fs.readFileSync(sourcePath)
+  const source = fs.readFileSync(sourcePath, "utf8")
 
 const tree = parser.parse(source)
```

**Comment by marijnh** [comment]
So can this be closed?

**Comment by milahu** [comment]
yes, sorry for the noise .__.

**Pull request closed without merging**
